version: '3.8'

services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    environment:
      - PORT=5055
      - MONGODB_URL=${MONGODB_URL}  # Ensure to set this in your .env file
      - JWT_SECRET=${JWT_SECRET}      # Ensure to set this in your .env file
    volumes:
      - .:/usr/src/app
